using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Thindal.Blazor.BindableParameter.SourceGenerator;
internal static class SourceGeneratorHelper
{
    public static void CreateParameter(SourceProductionContext context, ObservableParameterData data)
    {
        // Namespaces
        var usings = "using Microsoft.AspNetCore.Components;";

        // Create name of changed method
        var changedDukaMethodName = $"{data.PropertyName}Changed";

        // Create the event callbacks
        var eventCallback = $"[Parameter] public EventCallback<{data.PropertyType}> {changedDukaMethodName} {{get;set;}}";

        // Create calls of change callbacks
        var changedMethodsCalls = String.Join("\n\r", data.ChangedMethods.Select(m => $"{m}Changed.InvokeAsync(value);"));

        // Create the backing field
        // Create camelCased version of data.PropertyName
        var camelCasedPropertyName = char.ToLowerInvariant(data.PropertyName[0]) + data.PropertyName.Substring(1);
        var backingField = $"private {data.PropertyType} _{camelCasedPropertyName};";

        // Create the property
        var prop = $@"
[System.Diagnostics.CodeAnalysis.SuppressMessage(""Usage"", ""BL0007:Component parameters should be auto properties"", Justification = ""Generated by source generator"")]
[Parameter] public partial {data.PropertyType} {data.PropertyName}
{{
    get => _{camelCasedPropertyName};
    set {{
            if(_{camelCasedPropertyName} == value)
            {{
                return;
            }}

            _{camelCasedPropertyName} = value;
            {changedMethodsCalls}
        }}
}}";

        // Create the partial class
        var partialClass = $@"
{usings}
namespace {data.NamespaceName}
{{
    public partial class {data.ClassName}
    {{
        {backingField}
        {eventCallback}
        {prop}
    }}
}}";

        context.AddSource($"{data.ClassName}.{data.PropertyName}.BindableParameter.g.cs", partialClass);
    }
}
